version: "3.8"

services:
  mongodb:
    image: mongo:7.0-jammy
    container_name: stock-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7.2-alpine
    container_name: stock-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: stock-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/stock_dashboard
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=supersecretjwtkeyforstockdashboardintraday2026
      - JWT_REFRESH_SECRET=anotherrefreshsecretjwtkeyforstockdashboardintraday2026
      - CLIENT_API_URL=ws://backend:5000/mock-feed
      - NODE_ENV=production
    depends_on:
      - mongodb
      - redis

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    container_name: stock-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongodb_data:
  redis_data:
